--- #YAML:1.0
name:                Bundle-Parrot-Smoke
version:             0.01
abstract:            A bundle for installing all the modules needed to smoke Parrot
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Steve Peters <steve@fisharerojo.org>
